# file: roles/dotfiles/tasks/smt.yml

---
# files ------------------------------------------------------------------- {{{
- name: smt | mkdir -p dotfiles.smt.directories
  file: name={{ item }} state=directory
  with_items: dotfiles.smt.directories
# /files ------------------------------------------------------------------ }}}

# repos ------------------------------------------------------------------- {{{
- name: smt | git clone dotfiles.smt.git.repos
  git: repo={{ item.repo }} dest={{ item.dest }} accept_hostkey=true
  with_items: dotfiles.smt.git.repos
# /repos ------------------------------------------------------------------ }}}

# fzf --------------------------------------------------------------------- }}}
- name: smt | fzf install
  shell: "{{ dotfiles.smt.fzf.install }}"
# /fzf -------------------------------------------------------------------- }}}

# vim_plug ---------------------------------------------------------------- {{{
- name: smt | curl plug.vim
  shell: "{{ dotfiles.smt.vim_plug.download }}"
# /vim_plug --------------------------------------------------------------- {{{

# nvm --------------------------------------------------------------------- {{{
 - name: smt | nvm checkout
   shell: "{{ dotfiles.smt.nvm.commands.nvm_checkout }}"
# /nvm -------------------------------------------------------------------- }}}

# rbenv ------------------------------------------------------------------- {{{
 - name: smt | rbenv install dotfiles.smt.ruby.version
   shell: "{{ dotfiles.smt.rbenv.commands.rbenv_install_ruby }}"

 - name: smt | rbenv global dotfiles.smt.ruby.version
   shell: "{{ dotfiles.smt.rbenv.commands.rbenv_global_ruby }}"

 - name: smt | gem install bundler
   shell: "{{ dotfiles.smt.rbenv.commands.gem_install_bundler }}"
# /rbenv ------------------------------------------------------------------ }}}

# dotfiles ---------------------------------------------------------------- {{{
- name: smt | rake install dotfiles
  shell: "{{ dotfiles.smt.dotfiles.commands.install }}"

- name: smt | ln -s ~/.tmux.system.conf ~/.tmux.conf
  file: "src={{ smt.home }}/.tmux.{{ system }}.conf dest={{ smt.home }}/.tmux.conf state=link"
# /dotfiles --------------------------------------------------------------- }}}
